version: '3.5'

services:
  ft_traceroute:
    container_name: traceroute
    build: ..
    restart: on-failure
    networks:
      - mynetwork
    command: tail -f /dev/null

networks:
  mynetwork:
    driver: bridge
